### ISSUE TITLE
Flixbus feed has this error: "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#230]
https://transit.land/dispatcher/feeds/f-u-flixbus

`{:exception_log=>"\nundefined method `[]' for nil:NilClass\n...`

**Comment by drewda** [comment]
Lastest import: https://transit.land/dispatcher/feed-versions/fb70becf6f8ade27a8cbd92d55ee7827c393fbf4

Failing with:

```ruby
{:exception_log=>"\nChangeset::Error Couldn't find Stop\n[\"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/core.rb:196:in `find_by!'\", \"/www/transitland/releases/20170418191705/app/models/concerns/has_a_onestop_id.rb:33:in `find_by_onestop_id!'\", \"/www/transitland/releases/20170418191705/app/services/quality_check.rb:190:in `distances_between_rsp_stops'\", \"/www/transitland/releases/20170418191705/app/services/quality_check.rb:141:in `block (2 levels) in check'\", \"/www/transitland/releases/20170418191705/app/services/quality_check.rb:140:in `each_index'\", \"/www/transitland/releases/20170418191705/app/services/quality_check.rb:140:in `block in check'\", \"/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'\", \"/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'\", \"/www/transitland/releases/20170418191705/app/services/quality_check.rb:136:in `check'\", \"/www/transitland/releases/20170418191705/app/models/changeset.rb:186:in `check_quality'\", \"/www/transitland/releases/20170418191705/app/models/changeset.rb:289:in `block in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'\", \"/www/transitland/releases/20170418191705/app/models/changeset.rb:258:in `apply!'\", \"/www/transitland/releases/20170418191705/app/services/gtfs_graph.rb:183:in `create_change_osr'\", \"/www/transitland/releases/20170418191705/app/workers/feed_eater_worker.rb:29:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sentry-raven-2.4.0/lib/raven/integrations/sidekiq.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.0/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.0/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.0/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.0/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'\"]\n"}
```

@stevevance please add to the list on #226 and we'll track its progress there.
