### ISSUE TITLE
f-9qf-laketahoe~ca~us: Geohash divide by 0

### ISSUE THREAD

**Issue by irees** [transitland/transitland#73]
f-9qf-laketahoe~ca~us
```
{:exception_log=>"\ndivided by 0\n[\"/srv/www/transitland/releases/20160707003718/app/services/geohash_helpers.rb:79:in `/'\", \"/srv/www/transitland/releases/20160707003718/app/services/geohash_helpers.rb:79:in `centroid'\", \"/srv/www/transitland/releases/20160707003718/app/services/geohash_helpers.rb:86:in `fit'\", \"/srv/www/transitland/releases/20160707003718/app/models/operator.rb:134:in `from_gtfs'\", \"/srv/www/transitland/releases/20160707003718/app/services/gtfs_graph.rb:316:in `block in load_tl_operators'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/srv/www/transitland/releases/20160707003718/app/services/gtfs_graph.rb:311:in `load_tl_operators'\", \"/srv/www/transitland/releases/20160707003718/app/services/gtfs_graph.rb:37:in `create_change_osr'\", \"/srv/www/transitland/releases/20160707003718/app/workers/feed_eater_worker.rb:47:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]\n"}
```

**Comment by irees** [comment]
Agency with no stops:

```
 @agency_id="16",
 @agency_name="North Lake Tahoe Express - 24 hour advance reservations required",
```
